name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'         
  workflow_dispatch:       
    inputs:
      manualVersion:
        description: 'Override NuGet package version (optional, e.g., 1.2.3-preview)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity detailed

      - name: Determine package version
        id: get_version
        run: |
          if [ -n "${{ github.event.inputs.manualVersion }}" ]; then
            echo "Using manual version: ${{ github.event.inputs.manualVersion }}"
            echo "version=${{ github.event.inputs.manualVersion }}" >> $GITHUB_OUTPUT
          else
            echo "Using tag version: ${GITHUB_REF#refs/tags/v}"
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Pack NuGet package
        run: dotnet pack ./SimpleAppMetrics/SimpleAppMetrics/SimpleAppMetrics.csproj --no-build --configuration Release --output ./nupkgs /p:PackageVersion=${{ steps.get_version.outputs.version }}

      - name: Push NuGet package
        run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json